"""spec69 credit_card_account invoice

Spec 69 — cartão de crédito como entidade própria + fatura. Drift de
autogenerate em tabelas não relacionadas foi removido à mão — esta
migration toca SÓ as duas tabelas novas.

Revision ID: 61c2a45f658e
Revises: spec68c_kind_sub
Create Date: 2026-08-09 14:26:45.979827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c2a45f658e'
down_revision: Union[str, Sequence[str], None] = 'spec68c_kind_sub'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.Enum('BRL', 'USD', name='currency'), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('close_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institution.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_card_workspace', 'credit_card_account', ['workspace_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('credit_card_account_id', sa.String(length=36), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('iof_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('BRL', 'USD', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PAID', name='invoicestatus'), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['credit_card_account_id'], ['credit_card_account.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_workspace_status', 'invoice', ['workspace_id', 'status'], unique=False)
    op.create_index('ux_invoice_card_close', 'invoice', ['credit_card_account_id', 'close_date'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ux_invoice_card_close', table_name='invoice')
    op.drop_index('ix_invoice_workspace_status', table_name='invoice')
    op.drop_table('invoice')
    op.drop_index('ix_credit_card_workspace', table_name='credit_card_account')
    op.drop_table('credit_card_account')
    # ### end Alembic commands ###
